# =========================================
# Server Configuration
# =========================================
server:
  port: 8080 # Porta deste serviço

# =========================================
# Spring Boot Application Configuration
# =========================================
spring:
  application:
    name: project-management-service
  datasource:
    url: jdbc:postgresql://localhost:5432/buildingDB # <<< BANCO CENTRALIZADO
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# =========================================
# External Service URLs
# =========================================
auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:8083/api} # URL do Authentication Service
# Adicionar URLs para AP/AR/Employee/etc. se/quando forem chamados por este serviço
# payable:
#   service:
#     url: ${PAYABLE_SERVICE_URL:http://localhost:8088/api}
# receivable:
#   service:
#     url: ${RECEIVABLE_SERVICE_URL:http://localhost:8089/api}
# employee:
#   service:
#     url: ${EMPLOYEE_SERVICE_URL:http://localhost:8084/api}

# =========================================
# JWT Configuration (Este serviço VALIDA)
# =========================================
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970!} # <<< CHAVE IDÊNTICA

# =========================================
# Logging Configuration
# =========================================
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.bufalari.building: DEBUG # Pacote raiz deste serviço (confirmar pacote)
    org.hibernate.SQL: DEBUG

# =========================================
# Swagger/OpenAPI Configuration
# =========================================
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# =========================================
# Actuator Configuration
# =========================================
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: when_authorized