// Path: project-management-service/src/test/java/com/bufalari/building/ProjectManagementServiceApplicationTests.java
package com.bufalari.building; // Package name might also be renamed later if desired

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles; // Optional: Specify test profile

/**
 * Test class to verify that the Spring application context loads correctly
 * for the Project Management Service.
 * Classe de teste para verificar se o contexto da aplicação Spring carrega corretamente
 * para o Serviço de Gerenciamento de Projetos.
 */
@SpringBootTest // Indicates this is a Spring Boot integration test that loads the application context
// @ActiveProfiles("test") // Optional: Uncomment if you have specific configurations in application-test.yml
@ActiveProfiles("test")
class ProjectManagementServiceApplicationTests { // <<<--- RENAMED CLASS / CLASSE RENOMEADA ---<<<

	/**
	 * Default test generated by Spring Initializr.
	 * Simply tries to load the application context. If it fails, the test fails.
	 * Teste padrão gerado pelo Spring Initializr.
	 * Simplesmente tenta carregar o contexto da aplicação. Se falhar, o teste falha.
	 */
	@Test
	void contextLoads() {
		// This test method is intentionally empty.
		// O próprio carregamento do contexto pelo @SpringBootTest é o teste.
		// The loading of the context by @SpringBootTest is the test itself.
	}

}